on: push
name: Continuous Integration
jobs:
  Tests:
    name: base
    runs-on: ubuntu-latest
    container:
      image: i386/python:3.9-buster
    steps:
    - name: info
      run: |
        id
        pwd
        ls -hlA
        env
        ls /bin /usr/bin

    - name: checkout
      run: |
        git version
        git init .
        git remote add origin https://github.com/$GITHUB_REPOSITORY
        git config --local gc.auto 0
        git fetch --no-tags --prune --progress --no-recurse-submodules \
          --depth=1 origin +$GITHUB_SHA:refs/remotes/origin/${GITHUB_REF##*/}
        git checkout --progress --force -B ${GITHUB_REF##*/} \
          refs/remotes/origin/${GITHUB_REF##*/}
        git log -1 --format='%H'

    - name: setup java
      run: |
        apt update
        apt install -y openjdk-11-jdk-headless
      env:
        DEBIAN_FRONTEND: noninteractive

#   - uses: actions/setup-java@v1
#     with:
#       java-version: 12
#       architecture: x86
#   - name: install
#     run: |
#       linux32 --32bit i386 sh -c '
#         pip install --timeout=120 -U setuptools cython
#         pip install --timeout=120 .[dev,ci]
#       '
#   - name: test
#     run: |
#       linux32 --32bit i386 sh -c '
#         ant all
#         cd tests
#         CLASSPATH=../build/test-classes:../build/classes pytest -v
#       '
